import React from 'react';
import { Container } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import Footer from '../../Shared/Footer/Footer';
import FooterMobileNav from '../../Shared/FooterMobileNav/FooterMobileNav';
import Appbar from '../../Shared/Navbar/Appbar';
import './DataPrivacy.css'


const DataPrivacy = () => {
  const navigate = useNavigate()
    return (
        <div>
        <Appbar/>
        
         <Container className='my-5'>
           <div  className='text-start dataPrivacy-wraper mx-4'>
              <h3 id="topLine">Data Privacy Policy</h3> <br /> <br />
              <span onClick={()=>navigate(-1)} 
                className="arrow-back-btn backbtn-dataPrivacy ">
                            <i className="fa-solid fa-chevron-left"></i>
                </span>
              <h4>1. Introduction</h4>
              <p>
              Welcome to Varal Consultancy DMCC.Varal Consultancy DMCC.(“us”, “we”, or “our”) operates habot marketplace (hereinafter referred to as “Service” or “Habot” ). <br /> <br />
              Our Privacy Policy governs your visit to habot website, and explains how we collect, safeguard and disclose information that results from your use of our Service.We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Our Terms and Conditions ( “Terms” ) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ( “agreement” ).
              <hr />
              </p> <br />

              <h4>2. Definitions</h4>
              <h5>2.1 Service</h5>
              <p>Means the habot.io website operated by Varal Consultancy DMCC.</p> <br />

              <h5>2.2 Personal Data</h5>
              <p>
              Means any data relating to an identified natural person, or one who can be identified directly or indirectly by way of linking data, using identifiers such as name, voice, picture, identification number, online identifier, geographic location, or one or more special features that express the physical, psychological, economic, cultural or social identity of such person. It also includes Sensitive Personal Data and Biometric Data. 2.3. USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
              </p>

              <h5>2.3 Usage Data</h5>
              <p>
              is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
              </p>
              
              <h5>2.4 Cookies</h5>
              <p>
              Are small files stored on your device (computer or mobile device).
              </p>

              <h5>2.5 Data Processor (Or Service Provider)</h5>
              <p>
              Is an establishment or natural person who processes Personal Data on behalf of the Controller, as directed and instructed by the Controller.
              </p>

              <h5>2.6 Data Subject</h5>
              <p>
              Is any living individual who is the subject of Personal Data. 2.8. USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
              <hr /> <br />
              </p>

              <h4>3. Data Collection and Use</h4>
              <p>
              We collect several different types of information for various purposes to provide and improve our Service to you. 
              <hr /> <br />
              </p>

              <h4>4. Types of Data Collected</h4> <br />
           
              <h3>4.1. Personal Data</h3>
              <p> 4.1.1 While using our Service, we may ask you to </p>
                <ul className='privacy-list'>
                provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data” ). 
                Personally identifiable information may include, but is not limited to:
               <li> Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
               </ul>

              <div className='d-flex'>
              <p> 4.1.2</p>
              <p className='ms-2'> We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p> <br />
              </div>

              <h3>4.2 Data from Intergrated Services</h3> <br />
             
              <div className='d-flex'>
                <p> 4.2.1</p>
                <p className='ms-2'>
                  If you decide to register through or otherwise grant access to a Third Party “Integrated Service” such as Google, we may also collect Personal Data that is already associated with your Integrated Services account.
                </p>
              </div> <br />

              <div className='d-flex'>
                <p> 4.2.2</p>
                <p className='ms-2'>
                  If you choose to provide such information during registration, you are giving Habot the permission to use, share and store it in a manner consistent with this Privacy Policy.
                </p>
              </div> <br />

              <h3>4.3. Usage Data</h3>
              <div className='d-flex'>
                <p> 4.3.1</p>
                <p className='ms-2'>
                  We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data” ).
                </p>
              </div> <br />

              <div className='d-flex'>
                <p> 4.3.2</p>
                <p className='ms-2'>
                  This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
              </div> <br />

              <div className='d-flex'>
                <p> 4.3.3</p>
                <p className='ms-2'>
                  This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
              </div> <br /> 
              <h3>4.4 Location Data</h3> <br />
              <div className='d-flex'>
                <p> 4.4.1</p>
                <p className='ms-2'>
                We may use and store information about your location if you give us permission to do so (“Location Data” ). We use this data to provide features of our Service, to improve and customize our Service.
                </p>
              </div>

              <div className='d-flex'>
                <p> 4.4.2</p>
                <p className='ms-2'>
                You can enable or disable location services when you use our Service at any time by way of your device settings. 
                </p>
              </div> <br /> <br />

              <h3>4.5 Tracking Cookies Data</h3> <br />
              <div className='d-flex'>
                <p> 4.5.1</p>
                <p className='ms-2'>
                 We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                </p>
              </div> 
              <div className='d-flex'>
                <p> 4.5.2</p>
                <p className='ms-2'>
                 Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
                </p>
              </div> 
              <div className='d-flex'>
                <p> 4.5.3</p>
                <p className='ms-2'>
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
              </div> <br />
              <ul className='privacy-list'>
              Examples of Cookies we use:
               <li> Session Cookies: We use Session Cookies to operate our Service.</li>
                <li>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
                <li>Security Cookies: We use Security Cookies for security purposes.</li>
                <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                <li>Advertising Cookies:Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interest</li>
               </ul> <br />

               <h3>4.6 Other Data</h3>
               <div>
                <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on marital status, family members, social security (or other taxpayer identification) number, office location and other.</p>
              </div> <br />
              <hr />
              <br />
              <br />
              <h3>5. Use of Data</h3> <br />
              <div className='d-flex'>
                <p className="fw-bold">5.1</p>
                <p className='ms-2'>
                 Varal Consultancy DMCC uses the collected data for various purposes:
                </p>
              </div>
              <div className='d-flex'>
                <p>5.1.1</p>
                <p className='ms-2'>
                to provide and maintain our Service;
                </p>
              </div>
              <div className='d-flex'>
                <p>5.1.2</p>
                <p className='ms-2'>
                to notify you about changes to our Service;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.3</p>
                <p className='ms-2'>
                 to allow you to participate in interactive features of our Service when you choose to do so;
                </p>
              </div>

              <div className='d-flex'>
                <p>5.1.4</p>
                <p className='ms-2'>
                to provide customer support;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.5</p>
                <p className='ms-2'>
                to gather analysis or valuable information so that we can improve our Service;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.6</p>
                <p className='ms-2'>
                to monitor the usage of our Service;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.7</p>
                <p className='ms-2'>
                to detect, prevent and address technical issues;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.8</p>
                <p className='ms-2'>
                to fulfill any other purpose for which you provide it;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.9</p>
                <p className='ms-2'>
                to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
                </p>
              </div>

              <div className='d-flex'>
                <p>5.1.10</p>
                <p className='ms-2'>
                  to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.11</p>
                <p className='ms-2'>
                to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
                </p>
              </div> 

              <div className='d-flex'>
                <p>5.1.12</p>
                <p className='ms-2'>
                in any other way we may describe when you provide the information;
                </p>
              </div>

              <div className='d-flex'>
                <p>5.1.13</p>
                <p className='ms-2'>
                for any other purpose with your consent.
                </p>
              </div> <br /> 
              <hr /> <br />
           
              <h3>6. Retention of Data</h3>
              <div className='d-flex'>
                <p className="fw-bold">6.1</p>
                <p className='ms-2'>
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
              </div>

              <div className='d-flex'>
                <p className="fw-bold">6.2</p>
                <p className='ms-2'>
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>
              </div> <br />  
              <hr /> <br />

              <h3>7. Transfer of Data</h3> 
              <div className='d-flex'>
                <p className="fw-bold">7.1</p>
                <p className='ms-2'>
                Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                </p>
              </div>             
              <div className='d-flex'>
                <p className="fw-bold">7.2</p>
                <p className='ms-2'>
                 If you are located outside the United Arab Emirates and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United Arab Emirates and process it there.
                </p>
              </div>             
              <div className='d-flex'>
                <p className="fw-bold">7.3</p>
                <p className='ms-2'>
                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
              </div>             
              <div className='d-flex'>
                <p className="fw-bold">7.4</p>
                <p className='ms-2'>
                Varal Consultancy DMCC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>
              </div>    <br />
              <hr /> <br />
              
              <h3>8. Disclosure of Data</h3>   <br />
              <p>We may disclose the following personal information that we collect, or you provide:</p>   <br />
                <h4>Disclosure for Law Enforcement.</h4>  
              <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>  
             <h4>8.2 Business Transaction</h4>
             <p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>

             <h4>8.3 Other cases. We may disclose your information also:</h4> <br />
             <div className='d-flex'>
                <p>8.3.1</p>
                <p className='ms-2'>
                to our subsidiaries and affiliates;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.2</p>
                <p className='ms-2'>
                to contractors, service providers, and other third parties we use to support our business;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.3</p>
                <p className='ms-2'>
                to fulfill the purpose for which you provide it;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.4</p>
                <p className='ms-2'>
                for the purpose of including your company’s logo on our website;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.5</p>
                <p className='ms-2'>
                for any other purpose disclosed by us when you provide the information;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.6</p>
                <p className='ms-2'>
                with your consent in any other cases;
                </p>
              </div> 
             <div className='d-flex'>
                <p>8.3.7</p>
                <p className='ms-2'>
                if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
                </p>
              </div> 
              <br /> <hr /> <br />

              <h3>9. Security of Data</h3> <br />
              <p>
              The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p> <br />
              <hr />
              <br />

              <h3>10. Your Data Protection Rights Under Federal Decree-Law no. 45 of 2021</h3>
              <p>
              You have the right to know that the UAE government provides data regulation that ultimately comprises a patchwork of various data provisions derived from its Penal code, Constitution, Cyber Crime Law.
              </p>
               <h4>
               10.1. Right to obtain information
               </h4>
               <p>You have the right to be told about what aspects of and how your Personal Data is being processed. Whilst there is no express requirement for businesses to use privacy notices, their use could assist in securing compliance with this requirement amongst others.</p>
                
               <h4>10.2. Right to access</h4>
               <p>You have the right to obtain access to your Personal Data</p>
                
               <h4>10.3. Right to request Personal Data transfer</h4>
               <p>You have the right to request that the Personal Data is moved from one business to another (e.g. if they decide to change service provider).</p>
                
               <h4>10.4. Right to correction or erasure</h4>
               <p>You have the right to require inaccurate information about yourself to be corrected and have the right to have your Personal Data erased if it is no longer required for the purpose for which it was collected.</p>
                
               <h4>10.5. Right to restrict or stop processing</h4>
               <p>You may require businesses to restrict or stop processing their Personal Data in certain circumstances.</p>
                
               <h4>10.6. Right to file a complaint</h4>
               <p>You have the right to file a complaint with the UAE Data Office.
              
               </p>
                
               <h4>10.7. Right to withdraw consent</h4>
               <p>At any time you can withdraw consent they have given a business to process your Personal Data.
               </p> <br />
               <hr />
               <br />

               <h3>
               11. Service Providers
               </h3>
               <div className='d-flex'>
                <p className="fw-bold">11.1.</p>
                <p className='ms-2'>
                We may employ third party companies and individuals to facilitate our Service (“Service Providers” ), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
                </p>
              </div> 
               <div className='d-flex'>
               <p className="fw-bold">11.2.</p>
                <p className='ms-2'>
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
              </div> <br />
              <hr />
              <br />
              <h3>
               12. Analytics
               </h3>
               <p>
               We may use third-party Service Providers to monitor and analyze the use of our Service.
               </p>
               <br />
              <hr />
              <br />
              <h3>
                13. CI/CD Tools
              </h3>
              <p>
              We may use third-party Service Providers to automate the development process of our Service.
              </p>
              <br />
              <hr />
              <br />
              <h3>
               14. Behavioral Marketing
              </h3>
              <p>
              We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party suppliers use cookies to inform, optimize and serve ads based on your past visits to our Service.
              </p>
              <br />
              <hr />
              <br />
              <h3>
              15. Payments
              </h3>
              <div className='d-flex'>
               <p className="fw-bold">15.1.</p>
                <p className='ms-2'>
                We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
                </p>
              </div> 
              <div className='d-flex'>
               <p className="fw-bold">15.2.</p>
                <p className='ms-2'>
                We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                </p>
              </div> 
              <br /> 
              <hr />
              <br />
              <h3>
              16. Links to other Sites
              </h3>
              <div className='d-flex'>
               <p className="fw-bold">16.1.</p>
                <p className='ms-2'>
                Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
              </div> 
              <div className='d-flex'>
               <p className="fw-bold">16.2.</p>
                <p className='ms-2'>
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </div> 
              <br /> 
              <hr />
              <br />
              <h3>
               17. Children’s Privacy
              </h3>
              <div className='d-flex'>
               <p className="fw-bold">17.1.</p>
                <p className='ms-2'>
                Our Services are not intended for use by children under the age of 18 (“Child” or “Children” ).
                </p>
              </div> 
              <div className='d-flex'>
               <p className="fw-bold">17.2.</p>
                <p className='ms-2'>
                We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
              </div> 
              <br /> 
              <hr />
              <br />
              <h3>
              18. Changes to This Privacy Policy
              </h3>
              <div className='d-flex'>
               <p className="fw-bold">18.1.</p>
                <p className='ms-2'>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
              </div> 
              <div className='d-flex'>
               <p className="fw-bold">18.2.</p>
                <p className='ms-2'>
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
                </p>
              </div> 
              <div className='d-flex'>
               <p className="fw-bold">18.3.</p>
                <p className='ms-2'>
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </div> <br />
              <hr />
              <br />
              <h3>19. Contact Us</h3>
              <p>
              If you have any questions about this Privacy Policy, please contact us through our live chat.
              </p>
              <br />
              <div className='text-center'>
                <a href='#topLine' id="topArrow"><i class="fa-solid fa-arrow-up"></i></a>
              </div>



           </div>
         </Container>

        <FooterMobileNav/>
        <Footer/>
        </div>
    );
};

export default DataPrivacy;